//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatClient.IntroductionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntroductionService.IIntroductionService")]
    public interface IIntroductionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntroductionService/Introduce", ReplyAction="http://tempuri.org/IIntroductionService/IntroduceResponse")]
        bool Introduce(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntroductionService/Introduce", ReplyAction="http://tempuri.org/IIntroductionService/IntroduceResponse")]
        System.Threading.Tasks.Task<bool> IntroduceAsync(string str);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntroductionServiceChannel : FatClient.IntroductionService.IIntroductionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntroductionServiceClient : System.ServiceModel.ClientBase<FatClient.IntroductionService.IIntroductionService>, FatClient.IntroductionService.IIntroductionService {
        
        public IntroductionServiceClient() {
        }
        
        public IntroductionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntroductionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntroductionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntroductionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Introduce(string str) {
            return base.Channel.Introduce(str);
        }
        
        public System.Threading.Tasks.Task<bool> IntroduceAsync(string str) {
            return base.Channel.IntroduceAsync(str);
        }
    }
}
